### ISSUE TITLE
Can not remove Rancher: invalid memory address or nil pointer dereference 

### ISSUE THREAD

**Issue by MWallenberg** [rancher/system-tools#15]
I have installed a HA-installation of Rancher, using AirGap, as per the documentation. I then attempt to remove this installation with system-tools (I need to change the settings I defined when installing Rancher). I use the OSX-release (darwin), and run the following command:

```bash
./system-tools remove --kubeconfig ~/.kube/config 
```

The command runs a bit, and then crashes with the following output:

```
Are you sure you want to remove Rancher Management Plane in Namespace [cattle-system] [y/n]: y
INFO[0003] Removing Rancher management plane in namespace: [cattle-system] 
INFO[0003] Getting conenction configuration
[...lots of rows, removed for brevity...]
INFO[0022] Checking API resource [sourcecodeproviderconfigs] 
INFO[0022] Checking API resource [pipelinesettings]     
INFO[0022] Checking API resource [sourcecodecredentials] 
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1d21949]

goroutine 1 [running]:
github.com/rancher/system-tools/vendor/github.com/urfave/cli.HandleAction.func1(0xc4222c7a10)
	/go/src/github.com/rancher/system-tools/vendor/github.com/urfave/cli/app.go:472 +0x2c8
panic(0x1e96140, 0x2a80b40)
	/usr/local/go/src/runtime/panic.go:491 +0x283
github.com/rancher/system-tools/remove.getGroupAPIResourceList(0xc4200d0780, 0x0, 0x0, 0x0, 0x0, 0xc42058f030, 0xe, 0xc420894f40, 0x1, 0x1, ...)
	/go/src/github.com/rancher/system-tools/remove/remove.go:424 +0xa9
github.com/rancher/system-tools/remove.removeCattleAnnotationsFinalizersLabels(0xc4200d0780, 0x0, 0x0)
	/go/src/github.com/rancher/system-tools/remove/remove.go:475 +0x90d
github.com/rancher/system-tools/remove.DoRemoveRancher.func4(0x0, 0x0)
	/go/src/github.com/rancher/system-tools/remove/remove.go:92 +0x2a
github.com/rancher/system-tools/utils.RetryWithCount(0xc4222c73d8, 0x3, 0x0, 0x0)
	/go/src/github.com/rancher/system-tools/utils/utils.go:53 +0x62
github.com/rancher/system-tools/remove.DoRemoveRancher(0xc4200d0780, 0x0, 0x0)
	/go/src/github.com/rancher/system-tools/remove/remove.go:91 +0x35d
reflect.Value.call(0x1e30620, 0x20c8950, 0x13, 0x20483a7, 0x4, 0xc42004b9b0, 0x1, 0x1, 0xc42004b930, 0x2010bc0, ...)
	/usr/local/go/src/reflect/value.go:434 +0x905
reflect.Value.Call(0x1e30620, 0x20c8950, 0x13, 0xc42004b9b0, 0x1, 0x1, 0xc4200d0780, 0x2f7f8f8, 0x0)
	/usr/local/go/src/reflect/value.go:302 +0xa4
github.com/rancher/system-tools/vendor/github.com/urfave/cli.HandleAction(0x1e30620, 0x20c8950, 0xc4200d0780, 0x0, 0x0)
	/go/src/github.com/rancher/system-tools/vendor/github.com/urfave/cli/app.go:481 +0x180
github.com/rancher/system-tools/vendor/github.com/urfave/cli.Command.Run(0x204a729, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x206f3a2, 0x2a, 0x0, ...)
	/go/src/github.com/rancher/system-tools/vendor/github.com/urfave/cli/command.go:186 +0x9ed
github.com/rancher/system-tools/vendor/github.com/urfave/cli.(*App).Run(0xc420358f00, 0xc42008a080, 0x4, 0x4, 0x0, 0x0)
	/go/src/github.com/rancher/system-tools/vendor/github.com/urfave/cli/app.go:235 +0x57d
main.main()
	/go/src/github.com/rancher/system-tools/main.go:58 +0x497
```

I have tried running the linux-version of system tools (from a linux machine, obviously) with the same results. I have tried specifying namespace (cattle-system) with the same result. Could anyone please advice how I could fix this?

**Comment by MWallenberg** [comment]
I'm fumbling here, but I noticed the namespace was changed for clusterrolecredentials a few months back. Could this be it?

https://github.com/rancher/rancher/pull/16171/files

**Comment by superseb** [comment]
I'll take a look at this, what versions did you use (system-tools, RKE, k8s, Rancher)

**Comment by MWallenberg** [comment]
Rancher: 2.1.5
rke: 0.1.14
k8s: Installed via RKE, I don't know which version was installed.
system-tools: 0.1.0

I have been able to proceed by draining the node, stopping and deleting all docker containers, as well as removing local etcd-files. That was enough to allow me to start from scratch.

**Comment by superseb** [comment]
Can you share output of:

* `kubectl api-versions`
* `kubectl api-resources -o wide`
* `kubectl get crd`

I can fix the NPE but want to know why it's broken first.

**Comment by wesmcnamee-avalara** [comment]
I'm seeing the same problem when removing rancher from Kubernetes on Docker-Desktop

```
$ ./system-tools remove --kubeconfig ./config --namespace cattle-system
...
INFO[0005] Checking API resource [stacks/scale]
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1c808ac]

goroutine 1 [running]:
github.com/rancher/system-tools/vendor/github.com/urfave/cli.HandleAction.func1(0xc00094fa38)
	/go/src/github.com/rancher/system-tools/vendor/github.com/urfave/cli/app.go:472 +0x278
panic(0x1dea120, 0x2d25460)
	/usr/local/go/src/runtime/panic.go:513 +0x1b9
github.com/rancher/system-tools/remove.getGroupAPIResourceList(0xc0000f2780, 0x0, 0x0, 0x0, 0x0, 0xc0008f63b0, 0xe, 0xc0008fbb00, 0x1, 0x1, ...)
	/go/src/github.com/rancher/system-tools/remove/remove.go:424 +0x9c
github.com/rancher/system-tools/remove.removeCattleAnnotationsFinalizersLabels(0xc0000f2780, 0x0, 0x0)
	/go/src/github.com/rancher/system-tools/remove/remove.go:475 +0x18c
github.com/rancher/system-tools/remove.DoRemoveRancher.func4(0x0, 0x0)
	/go/src/github.com/rancher/system-tools/remove/remove.go:92 +0x2a
github.com/rancher/system-tools/utils.RetryWithCount(0xc00094f408, 0x3, 0x0, 0x0)
	/go/src/github.com/rancher/system-tools/utils/utils.go:53 +0x61
github.com/rancher/system-tools/remove.DoRemoveRancher(0xc0000f2780, 0x0, 0x0)
	/go/src/github.com/rancher/system-tools/remove/remove.go:91 +0x373
reflect.Value.call(0x1d82780, 0x2010fa0, 0x13, 0x1f8f59d, 0x4, 0xc0003e39d8, 0x1, 0x1, 0xc0005c2300, 0xc00051f130, ...)
	/usr/local/go/src/reflect/value.go:447 +0x449
reflect.Value.Call(0x1d82780, 0x2010fa0, 0x13, 0xc0003e39d8, 0x1, 0x1, 0x5, 0x4, 0xc00058ea70)
	/usr/local/go/src/reflect/value.go:308 +0xa4
github.com/rancher/system-tools/vendor/github.com/urfave/cli.HandleAction(0x1d82780, 0x2010fa0, 0xc0000f2780, 0x0, 0x0)
	/go/src/github.com/rancher/system-tools/vendor/github.com/urfave/cli/app.go:481 +0x1fb
github.com/rancher/system-tools/vendor/github.com/urfave/cli.Command.Run(0x1f919be, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1fb71bb, 0x2a, 0x0, ...)
	/go/src/github.com/rancher/system-tools/vendor/github.com/urfave/cli/command.go:186 +0x8f6
github.com/rancher/system-tools/vendor/github.com/urfave/cli.(*App).Run(0xc00047a780, 0xc0000381e0, 0x6, 0x6, 0x0, 0x0)
	/go/src/github.com/rancher/system-tools/vendor/github.com/urfave/cli/app.go:235 +0x52e
main.main()
	/go/src/github.com/rancher/system-tools/main.go:58 +0x442
```

**Comment by wesmcnamee-avalara** [comment]
@superseb 

```
$ kubectl api-versions
admissionregistration.k8s.io/v1beta1
apiextensions.k8s.io/v1beta1
apiregistration.k8s.io/v1
apiregistration.k8s.io/v1beta1
apps/v1
apps/v1beta1
apps/v1beta2
argoproj.io/v1alpha1
authentication.k8s.io/v1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1
authorization.k8s.io/v1beta1
autoscaling/v1
autoscaling/v2beta1
autoscaling/v2beta2
batch/v1
batch/v1beta1
certificates.k8s.io/v1beta1
compose.docker.com/v1beta1
compose.docker.com/v1beta2
coordination.k8s.io/v1beta1
events.k8s.io/v1beta1
extensions/v1beta1
metrics.k8s.io/v1beta1
networking.k8s.io/v1
policy/v1beta1
rbac.authorization.k8s.io/v1
rbac.authorization.k8s.io/v1beta1
scheduling.k8s.io/v1beta1
storage.k8s.io/v1
storage.k8s.io/v1beta1
v1
```

```
$ kubectl get crd
NAME                    CREATED AT
workflows.argoproj.io   2019-02-20T01:03:52Z
```

Something appears to be problematic with metrics, as using `-o wide` on the api-resources subcommand gives me this:
```
$ kubectl api-resources -o wide
error: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request
```
Hopefully this is unrelated.

**Comment by wesmcnamee-avalara** [comment]
I fixed the metrics problem by reinstalling metrics server `helm install stable/metrics-server` and that fixed the removal script.

**Comment by henshitou** [comment]
follow up this link can clean up rancher cluster completely: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/

**Comment by jiaqiluo** [comment]
This issue is moved and tracked under rancher/rancher https://github.com/rancher/rancher/issues/20918

Should you have new issues found for system-tool, please log the issue under rancher/rancher
https://github.com/rancher/rancher/issues
